
// Objective-C API for talking to the following Go packages
//
//	b0pass
//
// File is generated by gomobile bind. Do not edit.
#ifndef __B0pass_FRAMEWORK_H__
#define __B0pass_FRAMEWORK_H__

#include "B0pass.objc.h"
#include "Universe.objc.h"

#endif
