// Objective-C API for talking to b0pass Go package.
//   gobind -lang=objc b0pass
//
// File is generated by gobind. Do not edit.

#ifndef __B0pass_H__
#define __B0pass_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * 对外暴露两个方法。 一个 运行go程序
 */
FOUNDATION_EXPORT NSString* _Nonnull B0passRun(void);

/**
 * 一个停止go程序
 */
FOUNDATION_EXPORT NSString* _Nonnull B0passStop(void);

#endif
